### ISSUE TITLE
[TASK] evaluate bun

### ISSUE THREAD

**Issue by sebastianwessel** [sebastianwessel/purista#74]
Evaluate if purists is working on https://bun.sh

**Comment by Jarred-Sumner** [comment]
Let me know if you have any feedback on Bun

**Comment by sebastianwessel** [comment]
> Let me know if you have any feedback about Bun

Pretty cool @Jarred-Sumner 
Worked out of the box, faster than ts-node overall and also much faster on running tests.

There were some methods not implemented to be full api compatible with jest.  
But these where minor methods which can be worked around and also the missing parts on the roadmap.

So overall: pretty nice experience!
